import {
  BriefcaseBusiness,
  CircleHelp,
  FileCode2,
  FileText,
  Folder,
  List,
  Mail,
  Newspaper,
  Search,
  Settings2,
  Terminal,
  UserRound,
} from "lucide-react"
import { aboutText, buildLogText, projects } from "../data/portfolioData.js"

export const appMeta = {
  about: {
    id: "about",
    label: "About",
    icon: UserRound,
    route: "/about",
    x: 112,
    y: 18,
    width: 500,
    height: 610,
    minWidth: 420,
    minHeight: 430,
  },
  blog: {
    id: "blog",
    label: "Blog",
    icon: Newspaper,
    route: "/blog",
    x: 230,
    y: 44,
    width: 940,
    height: 535,
    minWidth: 520,
    minHeight: 350,
  },
  contact: {
    id: "contact",
    label: "Contact",
    icon: Mail,
    route: "/contact",
    x: 570,
    y: 18,
    width: 500,
    height: 610,
    minWidth: 420,
    minHeight: 500,
  },
  experience: {
    id: "experience",
    label: "Experience",
    icon: List,
    route: "/experience",
    x: 330,
    y: 28,
    width: 780,
    height: 600,
    minWidth: 520,
    minHeight: 410,
  },
  help: {
    id: "help",
    label: "Help",
    icon: CircleHelp,
    route: "/help",
    x: 310,
    y: 70,
    width: 860,
    height: 505,
    minWidth: 500,
    minHeight: 340,
  },
  settings: {
    id: "settings",
    label: "Settings",
    icon: Settings2,
    route: "/settings",
    x: 270,
    y: 24,
    width: 900,
    height: 600,
    minWidth: 520,
    minHeight: 440,
  },
  terminal: {
    id: "terminal",
    label: "Terminal",
    icon: Terminal,
    route: "/terminal",
    x: 200,
    y: 62,
    width: 920,
    height: 545,
    minWidth: 480,
    minHeight: 330,
  },
  works: {
    id: "works",
    label: "Works",
    icon: BriefcaseBusiness,
    route: "/works",
    x: 150,
    y: 8,
    width: 1080,
    height: 600,
    minWidth: 600,
    minHeight: 420,
  },
  "about-file": {
    id: "about-file",
    label: "about.txt",
    icon: FileText,
    route: "/desktop/about.txt",
    x: 400,
    y: 92,
    width: 580,
    height: 420,
    minWidth: 360,
    minHeight: 260,
    meta: `${aboutText.length} chars`,
  },
  "build-log-file": {
    id: "build-log-file",
    label: "build-log.md",
    icon: FileText,
    route: "/desktop/build-log.md",
    x: 450,
    y: 112,
    width: 600,
    height: 430,
    minWidth: 360,
    minHeight: 260,
    meta: `${buildLogText.length} chars`,
  },
}

for (const [index, project] of projects.entries()) {
  appMeta[`folder-${project.slug}`] = {
    id: `folder-${project.slug}`,
    label: project.title,
    icon: Folder,
    route: `/desktop/${project.slug}`,
    x: 170 + index * 64,
    y: 32 + index * 42,
    width: 620,
    height: 470,
    minWidth: 420,
    minHeight: 300,
    meta: "4 items",
  }
  appMeta[`project-${project.slug}`] = {
    id: `project-${project.slug}`,
    label: project.title,
    icon: FileCode2,
    route: `/works/${project.slug}`,
    x: 54 + index * 30,
    y: 8 + index * 14,
    width: 1080,
    height: 600,
    minWidth: 650,
    minHeight: 420,
    meta: "CASE STUDY",
  }
}

export const dockApps = [
  "about",
  "blog",
  "contact",
  "experience",
  "help",
  "search",
  "settings",
  "terminal",
  "works",
]

export const dockMeta = {
  ...appMeta,
  search: { id: "search", label: "Search", icon: Search },
}

export const desktopItems = [
  ...projects.map((project) => ({
    id: `folder-${project.slug}`,
    label: project.shortTitle,
    type: "folder",
  })),
  { id: "contact", label: "Contact", type: "app" },
  { id: "about-file", label: "about.txt", type: "text" },
  { id: "build-log-file", label: "build-log.md", type: "text" },
]
